version: '3.8'

# --------------------------------------------------------------------------
#  Traefik Service
# --------------------------------------------------------------------------
#  This file contains the configuration for running the blog with a Traefik
#  reverse proxy. It relies on Traefik to handle incoming traffic, SSL,
#  and routing.
#
#  To use: Deploy this service alongside your Traefik stack.
# --------------------------------------------------------------------------

services:
  blog-with-traefik:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: everything-markdown-blog
    restart: unless-stopped
    networks:
      - traefik # Must connect to Traefik's network
    labels:
      # --- Traefik Labels ---
      - "traefik.enable=true"

      # --- HTTP Router Definition ---
      - "traefik.http.routers.blog.rule=Host(`${SITE_URL}`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=stepupresolver"

      # --- Middlewares (Optional) ---
      - "traefik.http.routers.blog.middlewares=crowdsec-midware@docker"

      # --- Service Definition ---
      - "traefik.http.services.blog.loadbalancer.server.port=80"

# --------------------------------------------------------------------------
#  Networks
# --------------------------------------------------------------------------
#  `traefik`: An external network that your Traefik container
#                   is also connected to.
# --------------------------------------------------------------------------
networks:
  traefik:
    external: true